### ISSUE TITLE
assign_esmo2020 missing parameter for residual disease

### ISSUE THREAD

**Issue by samuelcyleung** [TalhoukLab/EndoTools#6]
Hi @dchiu911 , I believe the ESMO2020 algorithm do require residual disease.

e.g. "Stage I–IVA p53abn endometrial carcinoma with myometrial invasion, with no residual disease" -> "high"

on caEndometrial, the variable "residual" corresponds to residual disease.

Could you please kindly update?

Many thanks.

**Comment by dchiu911** [comment]
Hi @samuelcyleung I didn't incorporate residual disease into ESMO 2020 because Jessica said the following for the NSMP project:

> 
![image](https://user-images.githubusercontent.com/8665632/132401450-a78bf17b-a278-4599-bfe0-06efc876c0d7.png)

And since that project uses data from different databases, some of which have and don't have residual disease, the standard definition was not used. Should we add a separate input and subsequent conditions for when we do have it? The resulting ESMO 2020 would not be consistently classified for cross-database projects, however.
