### ISSUE TITLE
assign_esmo* - parameter name, please use standardized variable name

### ISSUE THREAD

**Issue by samuelcyleung** [TalhoukLab/EndoTools#7]
Hi @dchiu911 , sorry, another one ... this is very minor but I think its best to use standardized variable name for the parameter name.

This only applies to "stage"

In your functions, the stage is assumed to have substage e.g. IIIC

The standard variable name "stage" does not have substages.  

It would be best if parameter could be renamed to "stage_full"

Many thanks.

**Comment by dchiu911** [comment]
Hi @samuelcyleung I wrote the functions with user-friendliness in mind, so that the parameters don't exactly match our standardized variable names (e.g. I used stage instead of stage_full to save some typing and instead document the function `?assign_esmo2013()` parameter `stage` with description "FIGO stage: I, II, III, IV with substages". Another example is when I reduced mmr_ihc_2 and mmr_ihc_4 to mmr2 and mmr4 respectively.)

But certainly if we are the main users we can agree to prioritize consistency, I'll make the changes throughout.
